version: '3'

services:
  postgres_db:
    image: postgres:latest
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - db_volume:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "ctr"

  postgres_gui:
    image: dpage/pgadmin4
    ports:
      - "80:80"
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: "msadler@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "trustno1"
    depends_on: 
      - postgres_db

  redis_db:
    build:
        context: src/redis_db
        dockerfile: Dockerfile
    image: ctr/redis
    ports:
      - "6379:6379"
    restart: always
    volumes:
      - redis_volume:/data

volumes:
  db_volume:
  redis_volume: