version: '3'

services:
  postgres_db:
    container_name: postgres_container
    image: postgres:latest
    ports:
      - "5432:5432"
    restart: unless-stopped
    volumes:
      - db_volume:/var/lib/postgresql/data

  postgres_gui:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    ports:
      - "${PGADMIN_PORT}:80"
    restart: unless-stopped
    depends_on: 
      - postgres_db

  redis_db:
    image: redis
    container_name: cache
    ports:
      - "6379:6379"
    restart: unless-stopped
    volumes:
      - redis_volume:/data
      
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    ports:
        - 5672:5672
        - 15672:15672

volumes:
  db_volume:
  redis_volume: